version: "3"

services:

  nginx:
    build:
      context: ./docker/dev/nginx
    env_file: env
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - .:/www

  php:
    build:
      context: ./docker/dev/php
    env_file: env
    links:
      - database
    volumes:
      - .:/www

  database:
    image: postgres:10.3-alpine
    volumes:
      - database:/var/lib/postgresql
    env_file: env

  adminer:
   image: adminer
   links:
     - database
   ports:
     - 8080:8080

volumes:
  database: ~
