data:
    image: unzeroun/base

fpm:
    build:        docker/php
    volumes_from: [ data ]
    links:        [ mysql ]
    volumes:      [ '.:/www' ]

mysql:
    build:        docker/mysql
    volumes_from: [ data ]
    environment:  { MYSQL_ROOT_PASSWORD: root }

nginx:
    image:        unzeroun/nginx
    volumes_from: [ data      ]
    links:        [ fpm       ]
    ports:        [ '80:80' ]
    volumes:      [ '.:/www'  ]

