version: "3"

services:

  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - .:/www

  php:
    build:
      context: ./docker/php
    links:
      - database
    volumes:
      - .:/www

  database:
    image: postgres:10.3-alpine
    volumes:
      - database:/var/lib/postgresql
    environment:
      POSTGRES_USER: veilleur
      POSTGRES_PASSWORD: veilleur

  adminer:
    image: adminer
    links:
      - database
    ports:
      - 8080:8080

volumes:
  database: ~
