parameters:
    locale: en
    slack_web_channel: '%env(SLACK_WEB_CHANNEL)%'

imports:
    - { resource: services.yml }

framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(APP_SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        name: veilleur
    fragments:       ~
    http_method_override: true
    assets: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        server_version: 10.3
        host:     "%env(POSTGRES_HOST)%"
        port:     "%env(POSTGRES_PORT)%"
        dbname:   "%env(POSTGRES_DB)%"
        user:     "%env(POSTGRES_USER)%"
        password: "%env(POSTGRES_PASSWORD)%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:  ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers: ["content-type", "authorization"]
        max_age:       3600
        expose_headers: ['Content-Disposition', 'Content-Length', 'Link']
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']

api_platform:
  title: "%env(API_NAME)%"
  description: "%env(API_DESCRIPTION)%"
