hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    path: /login/check-google

react_app:
  path: '{uri}'
  defaults: { _controller: 'FrameworkBundle:Template:template', template: 'react_app.html.twig' }
  condition: "request !== null and request.headers.get('Accept') matches '/html/i'"
  requirements: { uri: '.*' }

api_platform:
    resource: .
    type: api_platform

swagger_ui:
  path: /docs/api
  controller: api_platform.swagger.action.ui

app:
    resource: '../../src/AppBundle/Controller'
    type: annotation