services:
    monolog.formatter.colored_line:
        class: Bramus\Monolog\Formatter\ColoredLineFormatter

    guzzle.client:
        class: GuzzleHttp\Client

    repository.tag:
        class:     AppBundle\Entity\Repository\TagRepository
        factory:   [ '@doctrine.orm.default_entity_manager', 'getRepository' ]
        arguments: [ 'AppBundle:Tag' ]

    fetcher.guzzle:
        class:     AppBundle\Fetcher\GuzzleFetcher
        arguments: [ '@guzzle.client' ]

    extractor.watch_link_metadata:
        class:     AppBundle\Extractor\WatchLinkMetadataExtractor
        arguments: [ '@fetcher.guzzle', '@repository.tag' ]

    parser.slack_message:
        class: AppBundle\Parser\SlackMessageParser

    slack.api:
        class:     AppBundle\Api\SlackApi
        arguments: [ '@guzzle.client', '%slack_web_api_token%' ]

    'AppBundle\Filter\TagFilter':
        arguments: ["@doctrine"]

    'AppBundle\Filter\OverriddenFilter':
        arguments: ["@doctrine"]
