imports:
    - { resource: services/api.yml }

services:
    monolog.formatter.colored_line:
        class: Bramus\Monolog\Formatter\ColoredLineFormatter

    guzzle.client:
        class: GuzzleHttp\Client

    fetcher.guzzle:
        class:     AppBundle\Fetcher\GuzzleFetcher
        arguments: [ '@guzzle.client' ]

    extractor.watch_link_metadata:
        class:     AppBundle\Extractor\WatchLinkMetadataExtractor
        arguments: [ '@fetcher.guzzle' ]

    parser.slack_message:
        class: AppBundle\Parser\SlackMessageParser
